# Generated by Django 5.2.1 on 2025-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_department_manager',
            field=models.BooleanField(default=False, verbose_name='هل هو مدير إدارة؟'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr_staff',
            field=models.BooleanField(default=False, verbose_name='هل هو من شؤون الموظفين؟'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='الوظيفة'),
        ),
    ]
