# Generated by Django 5.2.1 on 2025-07-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_is_department_manager_employee_is_hr_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='القسم')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='account.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'أقسام',
                'unique_together': {('name', 'department')},
            },
        ),
    ]
