# Generated by Django 5.2.1 on 2025-07-25 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'موظفون',
            },
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='معرّف الجهاز (MAC)')),
                ('system', models.CharField(max_length=100, verbose_name='نظام التشغيل')),
                ('node', models.CharField(max_length=255, verbose_name='اسم الجهاز')),
                ('release', models.CharField(max_length=100, verbose_name='إصدار النظام')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='نسخة النظام')),
                ('machine', models.CharField(max_length=100, verbose_name='نوع المعالج')),
                ('processor', models.CharField(blank=True, max_length=255, null=True, verbose_name='المعالج')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ أول ظهور')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ملف تعريف الجهاز',
                'verbose_name_plural': 'ملفات تعريف الأجهزة',
                'unique_together': {('employee', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='التاريخ')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('is_late', models.BooleanField(default=False, verbose_name='تأخير دخول')),
                ('is_early_departure', models.BooleanField(default=False, verbose_name='مغادرة مبكرة')),
                ('late_duration', models.DurationField(blank=True, null=True, verbose_name='مدة التأخير')),
                ('early_departure_duration', models.DurationField(blank=True, null=True, verbose_name='مدة المغادرة المبكرة')),
                ('late_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحضور المتأخر')),
                ('early_exit_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الخروج المبكر')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='وكيل المستخدم')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور يومي',
                'verbose_name_plural': 'الحضور اليومي',
                'ordering': ['-attendance_date', 'employee__last_name'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
