# Generated by Django 5.2.1 on 2025-07-26 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SPECIAL_PERMISSION', 'إذن خاص'), ('BUSINESS_TRIP', 'مهمة عمل')], default='SPECIAL_PERMISSION', max_length=20, verbose_name='نوع الطلب')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('request_day', models.CharField(default='', max_length=20, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='الوقت من')),
                ('end_time', models.TimeField(verbose_name='الوقت إلى')),
                ('reason', models.TextField(verbose_name='البيان/السبب')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع (لمهمة العمل)')),
                ('requester_name', models.CharField(max_length=100, verbose_name='مقدم الطلب')),
                ('direct_manager_status', models.CharField(choices=[('PENDING', 'معلق'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة موافقة المسؤول المباشر')),
                ('direct_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('direct_manager_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المسؤول المباشر')),
                ('department_manager_status', models.CharField(choices=[('PENDING', 'معلق'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة موافقة مدير الإدارة')),
                ('department_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('department_manager_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات مدير الإدارة')),
                ('hr_status', models.CharField(choices=[('PENDING', 'معلق'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة موافقة شؤون الموظفين')),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات شؤون الموظفين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'طلب إذن',
                'verbose_name_plural': 'طلبات الإذن',
                'ordering': ['-created_at'],
            },
        ),
    ]
