# Generated by Django 5.2.1 on 2025-07-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('hr', '0002_permissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='account.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='account.employee', verbose_name='الموظف'),
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ['employee__user__last_name'], 'verbose_name': 'حضور يومي', 'verbose_name_plural': 'الحضور اليومي'},
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
